"""Version details for maluforce"""

__title__ = "maluforce"
__description__ = "A basic Salesforce and Pandas interface"
__url__ = "https://github.com/rodrigoelemesmo/maluforce"
__version__ = "0.0.2"
__author__ = "Rodrigo Maluf"
__author_email__ = "rodrigo1793@gmail.com"
__license__ = "None"
__maintainer__ = "Rodrigo Maluf"
__maintainer_email__ = "rodrigo1793@gmail.com"
__keywords__ = "python salesforce salesforce.com pandas"
